name: build

on:
  pull_request:
    branches:
      - cli/**
    types:
      - assigned
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow passed'
      - name: show tag
        run: echo ${{ github.ref }}