name: build

on:
  workflow_run:
    workflows: [AutoCreating SubMod Tags]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - name: show tag
        run: echo ${{ github.ref }}