name: build

on:
  pull_request:
    branches:
      - cli/**
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - run: echo 'The triggering workflow passed'
      - name: show tag
        run: echo ${{ github.ref }}