name: Test and coverage

on: 
  push:
    branches:
    - fix/**
  # pull_request:
  #   branches:
  #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - name: Run coverage
        run: |
          for file in `find . -name go.mod`; do
              dirpath=$(dirname $file)
              cd $dirpath
              go test ./... -v -race -coverprofile=coverage.out -covermode=atomic
              if grep -q "/gotest/.*/v2" go.mod; then
                  sed -i "s/gotest\(\/.*\)\/v2/gotest\/v2\1/g" coverage.out
              fi
              cd -
          done
      # - name: Run gotest coverage
      #   run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      # - name: Run sub coverage
      #   run: |
      #     cd sub
      #     go test -race -coverprofile=coverage.out -covermode=atomic
      # - name: Run add coverage
      #   run: |
      #     cd add
      #     go test -race -coverprofile=coverage.out -covermode=atomic
      #     sed -i "s/\/add\/v2/\/v2\/add/g" coverage.out
      # - name: Run cmd/sub coverage
      #   run: |
      #     cd cmd/sub
      #     go test -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
