name: test

on:
  push:
    branches:
      - master
      - coverage
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Auto Creating Tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.18", "1.19", "1.20", "1.21" ]
        goarch: [ "386", "amd64" ]
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v3
      - name: run
        run: whoami
      - name: run
        run: ls -l
      - name: run
        run: pwd
      - name: Setup Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
            ${{ runner.os }}-go-
            ${{ runner.os }}-
      - name: Build & Test
        if: ${{ (github.event_name == 'push' && github.ref != 'refs/heads/master') || github.event_name == 'pull_request' }}
        run: |
          go env GOMODCACHE
          go env GOCACHE
          echo ${{ github.ref }}
          bash ./test.sh
      - name: Build & Test & Coverage
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          echo ${{ github.ref }}
          bash ./test.sh coverage
      - name: show
        if: ${{ github.ref != 'refs/heads/coverage' }}
        run: echo ${{ github.ref }}
      - name: show
        if: ${{github.ref == 'refs/heads/coverage'}}
        run: echo ${{ github.ref }}
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'


      