name: test

on:
  push:
    branches:
      - master
      - coverage

jobs:
  build:
    name: Auto Creating Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v3
      - name: run
        run: whoami
      - name: run
        run: ls -l
      - name: run
        run: pwd
      - name: show
        if: ${{github.ref != 'refs/heads/coverage'}}
        run: echo ${{ github.ref }}
      - name: show
        if: ${{github.ref == 'refs/heads/coverage'}}
        run: echo ${{ github.ref }}
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
