name: AutoCreating SubMod Tags

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Auto Creating Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v3
      # - name: update dependencies
      #   run: make gftidy
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     commit-message: 'update gf to ${{ github.ref_name }}'
      #     title: Auto Tags
      #     base: master
      #     branch: myautotag
      #     delete-branch: true
      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: autotag
      #     author_name: TagRobot
      #     author_email: tagrobot@goframe.org
      #     message: 'update gf to ${{ github.ref_name }}'
      - name: Auto Creating Tags
        run: |
          git config --global user.email "tagrobot@goframe.org"
          git config --global user.name  "TagRobot"
          for file in `find contrib -name go.mod`; do
              tag=$(dirname $file)/${{ github.ref_name }}
              git tag $tag
              git push origin $tag
          done
      - name: update dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: make cliversion to=${{ github.ref_name }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: autotag
          author_name: TagRobot
          author_email: tagrobot@goframe.org
          message: 'update gfcli to ${{ github.ref_name }}'
      - name: Auto Creating Tags
        run: |
          git config --global user.email "tagrobot@goframe.org"
          git config --global user.name  "TagRobot"
          for file in `find cmd -name go.mod`; do
              tag=$(dirname $file)/${{ github.ref_name }}
              git tag $tag
              git push origin $tag
          done
