name: 自动打子包标签

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Auto Creating Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v4

          #         go env
          # go env -w GOPRIVATE=github.com/hailaz/gotest
          # go env
          # make cliversion to=${{ github.ref_name }}
      - name: update dependencies
        run: |
          go env -w GOPRIVATE=github.com/hailaz/gotest
          .github/workflows/version.sh ./cmd/gfly ${{ github.ref_name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'update gf cli to ${{ github.ref_name }}'
          title: tag ${{ github.ref_name }} update gf cli
          base: master
          branch: fix/${{ github.ref_name }}
          delete-branch: true
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: fix/${{ github.ref_name }}
          author_name: TagRobot
          author_email: tagrobot@goframe.org
          message: 'update gf cli to ${{ github.ref_name }}'
      - name: Auto Creating Tags
        run: |
          git config --global user.email "tagrobot@goframe.org"
          git config --global user.name  "TagRobot"
          for file in `find cmd -name go.mod`; do
              tag=$(dirname $file)/${{ github.ref_name }}
              git tag $tag
              git push origin $tag
          done
